### ISSUE TITLE
Migrate to null-safety

### ISSUE THREAD

**Issue by balthier82** [yasukotelin/ext_storage#11]
Any planning to migrate to null-safety?

**Comment by Amir-P** [comment]
It was pretty easy and I opened a pull request to add null-safety support. I hope the author have some time to check it. @balthier82

**Comment by chitgoks** [comment]
hope this gets updated

**Comment by viktor-savchik-idf** [comment]
are there any updates?
@yasukotelin

**Comment by lavahasif** [comment]
flutter clean
for null safety

```yaml
dependencies:
  ext_storage:
    git:
      url: git://github.com/GitJournal/ext_storage.git
```

**Comment by kosiara** [comment]
Thanks @Amir-P for providing an update and @lavahasif for forking it on github 🎁  You guys saved others time

**Comment by billysmt** [comment]
@lavahasif Any chance you could update your repo to be flutter 2.5 compatible?

**Comment by lavahasif** [comment]
@billysmt  Currently you can above git dependency it also work in 2.5 dependency .
if you feel any difficulty you can use this in 2.5 . i  build this plugin using 2.5 you can use this.

```yaml
dependencies:
  ext_storage:
    git:
      url: git://github.com/lavahasif/ext_storage_ups.git
```
